@MyPurchasedBook_HostAddress = https://localhost:7287

GET {{MyPurchasedBook_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MyPurchasedBook_HostAddress}}/api/Book/GetBook
Accept: application/json

###

POST {{MyPurchasedBook_HostAddress}}/api/book
Content-Type: application/json

{
  "Title":"",
  "ISBN":"",
  "Author":"",
  "Publisher":"",
  "PublishDate":"",
  "Categories":"",
  "Description":"",
  "Image":"",
  "ImageType":""
}


###

@TitleName=string
GET {{MyPurchasedBook_HostAddress}}/api/book/CheckTitleBook?TitleName={{TitleName}}

###

GET {{MyPurchasedBook_HostAddress}}/api/author/GetAuthorList

###

GET {{MyPurchasedBook_HostAddress}}/api/publisher/GetPublisherList

###

GET {{MyPurchasedBook_HostAddress}}/api/category/GetCategoryList

###

PUT {{MyPurchasedBook_HostAddress}}/api/book
Content-Type: application/json

{
  //Book
}

###

DELETE {{MyPurchasedBook_HostAddress}}/api/book/{{ISBN}}

###
