@MyPurchasedBook_HostAddress = https://localhost:7287

GET {{MyPurchasedBook_HostAddress}}/weatherforecast/
Accept: application/json

###

GET {{MyPurchasedBook_HostAddress}}/api/Book/GetBook
Accept: application/json

###

POST {{MyPurchasedBook_HostAddress}}/api/book
Content-Type: application/json

{
  //Book
}

###
